function D=fun_D(T,c_oxmol,c_oxwt,KD_ol,Dol_Mg,Dopx_Mg)

D=[fun_Dol_Ni(T,c_oxmol,c_oxwt,KD_ol),...
    fun_Dol_Mn(Dol_Mg),fun_Dol_V(),fun_Dol_Cr(Dol_Mg),...
    fun_Dol_Ti(),fun_Dol_Co(Dol_Mg),fun_Dol_Sc(Dol_Mg),fun_Dol_Zn();...
    fun_Dopx_Ni(Dopx_Mg),fun_Dopx_Mn(Dopx_Mg),...
    fun_Dopx_V(),fun_Dopx_Cr(Dopx_Mg),fun_Dopx_Ti(Dopx_Mg),...
    fun_Dopx_Co(Dopx_Mg),fun_Dopx_Sc(Dopx_Mg),fun_Dopx_Zn();...
    fun_Dcpx_Ni(),fun_Dcpx_Mn(),fun_Dcpx_V(),fun_Dcpx_Cr(),...
    fun_Dcpx_Ti(),fun_Dcpx_Co(),fun_Dcpx_Sc(),fun_Dcpx_Zn();...
    fun_Dplag_Ni(),fun_Dplag_Mn(),fun_Dplag_V(),fun_Dplag_Cr(),...
    fun_Dplag_Ti(),fun_Dplag_Co(),fun_Dplag_Sc(),fun_Dplag_Zn();...
    fun_Dsp_Ni(),fun_Dsp_Mn(),fun_Dsp_V(),fun_Dsp_Cr(),...
    fun_Dsp_Ti(),fun_Dsp_Co(),fun_Dsp_Sc(),fun_Dsp_Zn();...
    fun_Dgt_Ni(),fun_Dgt_Mn(),fun_Dgt_V(),fun_Dgt_Cr(),...
    fun_Dgt_Ti(),fun_Dgt_Co(),fun_Dgt_Sc(),fun_Dgt_Zn()];

end